[build]
  publish = ".next"
  command = "npm run build"
[[plugins]]
  package = "@netlify/plugin-nextjs"
[[redirects]]
  from = "/api/proxy/*"
  to = "https://prostastal-backend-5bd4ca6915d2.herokuapp.com/"
  status = 200
  force = true